# Generated by Django 5.0.1 on 2024-01-24 20:43

import django.db.models.deletion
import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0014_alter_cliente_complemento'),
        ('produto', '0025_alter_peca_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.ManyToManyField(related_name='CidadeRegião', to='representante.cidade')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('tel_principal', models.CharField(blank=True, max_length=14, null=True)),
                ('tel_contato', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('mei', models.CharField(blank=True, max_length=255, null=True)),
                ('insc_estadual', models.CharField(blank=True, max_length=15, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=11, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('status_representante', models.BooleanField(default=True, verbose_name='Ativo')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='representante.regiao')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=20)),
                ('representante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representante.representante')),
            ],
            options={
                'verbose_name': 'Dados Bancários',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
        migrations.CreateModel(
            name='ServicoRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('produto', models.ManyToManyField(related_name='ServiçoProdutos', to='produto.produto')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representante.representante')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['data_recebimento'],
            },
        ),
    ]
