# Generated by Django 4.1.7 on 2023-05-09 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("produto", "0001_initial"),
        ("transportadora", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CondicaoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("parcelas", models.IntegerField()),
                ("primeira", models.IntegerField()),
                ("demais", models.IntegerField()),
            ],
            options={
                "verbose_name": "Condição de pagamento",
                "verbose_name_plural": "Condições de pagamento",
            },
        ),
        migrations.CreateModel(
            name="StatusVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Status venda",
                "verbose_name_plural": "Status vendas",
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateField(default=datetime.date.today)),
                ("data_entrega", models.DateField()),
                ("codigo", models.CharField(blank=True, max_length=8)),
                ("vendedor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "valor_venda",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "desconto_venda",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "venda_desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                ("dias_prim_par", models.IntegerField()),
                ("dias_outras_par", models.IntegerField()),
                ("parcelas", models.IntegerField()),
                ("detalhes", models.CharField(blank=True, max_length=255, null=True)),
                ("atualizadoem", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.cliente",
                        verbose_name="CLIENTE",
                    ),
                ),
                (
                    "condicaopgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="venda.condicaovenda",
                    ),
                ),
                (
                    "status_venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="venda.statusvenda",
                    ),
                ),
                (
                    "transportadora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transportadora.transportadora",
                        verbose_name="TRANSPORTADORA",
                    ),
                ),
            ],
            options={
                "verbose_name": "VENDA",
                "verbose_name_plural": "VENDAS",
            },
        ),
        migrations.CreateModel(
            name="VendaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField(default=1)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="produto.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="venda.venda"
                    ),
                ),
            ],
            options={
                "verbose_name": "PRODUTO DA VENDA",
                "verbose_name_plural": "PRODUTOS DA VENDA",
            },
        ),
    ]
