# Generated by Django 4.1.7 on 2023-05-09 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0002_formapagamento_condicaovenda_formapgto"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="formapgto",
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
