# Generated by Django 4.1.7 on 2023-05-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0003_venda_formapgto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="formapgto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="venda.formapagamento"
            ),
        ),
    ]
