# Generated by Django 4.1.7 on 2023-05-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
        ("venda", "0004_alter_venda_formapgto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="clientevenda",
                to="cliente.cliente",
                verbose_name="CLIENTE",
            ),
        ),
    ]
