# Generated by Django 4.1.7 on 2023-05-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0006_limiteproducaodiaria"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LimiteProducaoDiaria",
        ),
    ]
