# Generated by Django 4.1.7 on 2023-05-29 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("venda", "0009_alter_venda_data_entrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaximoDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtde", models.IntegerField(default=10)),
            ],
        ),
        # migrations.RenameField(
        #     model_name="venda",
        #     old_name="desconto_venda",
        #     new_name="subtotal",
        # ),
        # migrations.RenameField(
        #     model_name="venda",
        #     old_name="venda_desconto",
        #     new_name="valor_desconto",
        # ),
        # migrations.RemoveField(
        #     model_name="venda",
        #     name="codigo",
        # ),
        # migrations.AddField(
        #     model_name="venda",
        #     name="porcentagem_desconto",
        #     field=models.IntegerField(default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name="venda",
            name="data_entrega",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
