# Generated by Django 4.1.7 on 2023-05-29 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("venda", "0010_maximodesconto_rename_desconto_venda_venda_subtotal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="desconto_venda",
            new_name="subtotal",
        ),
        migrations.RenameField(
            model_name="venda",
            old_name="venda_desconto",
            new_name="valor_desconto",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="codigo",
        ),
        migrations.AddField(
            model_name="venda",
            name="porcentagem_desconto",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
