# Generated by Django 4.1.7 on 2023-05-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0011_rename_desconto_venda_venda_subtotal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="porcentagem_desconto",
        ),
    ]
