# Generated by Django 4.1.7 on 2023-05-29 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("venda", "0012_remove_venda_porcentagem_desconto"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="porcentagem_desconto",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
