# Generated by Django 3.2.20 on 2023-07-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0013_venda_porcentagem_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_desconto',
        ),
        migrations.AlterField(
            model_name='venda',
            name='status_venda',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('autorizado', 'Autorizado'), ('emproducao', 'Em Produção'), ('expedicao', 'Expedição'), ('enviado', 'Enviado')], max_length=50),
        ),
        migrations.DeleteModel(
            name='StatusVenda',
        ),
    ]
