# Generated by Django 3.2.20 on 2023-07-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0014_auto_20230712_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adesivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ADESIVADO',
                'verbose_name_plural': 'ADESIVADOS',
            },
        ),
        migrations.CreateModel(
            name='Torneira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TORNEIRA',
                'verbose_name_plural': 'TORNEIRAS',
            },
        ),
        migrations.CreateModel(
            name='Voltagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'VOLTAGEM',
                'verbose_name_plural': 'VOLTAGENS',
            },
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='adesivado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='venda.adesivado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='torneira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='venda.torneira'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='voltagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='venda.voltagem'),
            preserve_default=False,
        ),
    ]
