# Generated by Django 3.2 on 2023-07-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0015_auto_20230712_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
