# Generated by Django 3.2.20 on 2023-09-06 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0016_venda_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atualizadopor',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
