# Generated by Django 3.2.20 on 2023-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0018_alter_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valortotalcomimposto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
    ]
