# Generated by Django 3.2.20 on 2023-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0019_venda_valortotalcomimposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='notafiscal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
