# Generated by Django 3.2.20 on 2023-10-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0023_auto_20231019_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='xml_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
