# Generated by Django 3.2.20 on 2023-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0024_venda_xml_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='xml_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
