# Generated by Django 3.2.20 on 2023-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0025_alter_venda_xml_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='xml_json',
        ),
        migrations.AddField(
            model_name='venda',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
