# Generated by Django 3.2.20 on 2023-10-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venda", "0026_auto_20231020_1636"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="url",
            new_name="danfe",
        ),
        migrations.AddField(
            model_name="venda",
            name="danfe_etiqueta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="danfe_simples",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="xml",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
