# Generated by Django 3.2.20 on 2023-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venda", "0027_auto_20231020_1705"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="danfe",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="danfe_etiqueta",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="danfe_simples",
        ),
        migrations.AddField(
            model_name="venda",
            name="numero_nf",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="status_venda",
            field=models.CharField(
                choices=[
                    ("orcamento", "Orçamento"),
                    ("autorizado", "Autorizado"),
                    ("emproducao", "Em Produção"),
                    ("expedicao", "Expedição"),
                    ("nfemitida", "Nota Fiscal Emitida"),
                    ("enviado", "Enviado"),
                ],
                max_length=50,
            ),
        ),
    ]
