# Generated by Django 3.2.20 on 2023-10-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0028_auto_20231024_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='danfe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='danfe_etiqueta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='danfe_simples',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
