# Generated by Django 3.2.20 on 2023-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0029_auto_20231024_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_mercadolivre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='taxa_mercadolivre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='porcentagem_desconto',
            field=models.IntegerField(default=0.0),
        ),
    ]
