# Generated by Django 3.2.20 on 2023-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0030_auto_20231029_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status_expedicao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
