# Generated by Django 3.2.20 on 2023-11-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0032_alter_venda_status_expedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_status_expedicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
