# Generated by Django 3.2.20 on 2023-11-21 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0033_venda_data_status_expedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
