# Generated by Django 3.2.20 on 2023-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0036_venda_cotacao_transportadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quemrecebe_mercadolivre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='telefonequemrecebe_mercadolivre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
