# Generated by Django 3.2.20 on 2023-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0037_auto_20231123_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='etiqueta_impressa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
