# Generated by Django 3.2.20 on 2023-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0038_vendaproduto_etiqueta_impressa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='etiqueta_impressa',
        ),
        migrations.AddField(
            model_name='venda',
            name='etiqueta_impressa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
