# Generated by Django 3.2.20 on 2023-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0039_auto_20231129_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status_expedicao',
            field=models.CharField(blank=True, default='Conferir dados', max_length=60, null=True),
        ),
    ]
