# Generated by Django 3.2.20 on 2023-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0040_alter_venda_status_expedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='urgente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
