# Generated by Django 3.2.20 on 2023-12-22 12:41

from django.db import migrations, models
import venda.models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0042_alter_venda_status_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=venda.models.path_and_receita_comprovante),
        ),
    ]
