# Generated by Django 3.2.20 on 2024-01-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0042_auto_20231218_1812'),
        ('venda', '0043_venda_comprovante'),
    ]

    operations = [
    ]
