# Generated by Django 3.2.20 on 2024-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0044_merge_0042_auto_20231218_1812_0043_venda_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='informacao_adicional_notafiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
