# Generated by Django 3.2.20 on 2024-03-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0045_venda_informacao_adicional_notafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nfjaimpressa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
