# Generated by Django 3.2.20 on 2024-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0047_venda_status_posvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_impresssao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
