# Generated by Django 3.2.20 on 2024-03-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0048_venda_data_impresssao"),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='venda',
    #         old_name='data_impresssao',
    #         new_name='data_impressao',
    #     ),
    # ]
