# Generated by Django 3.2.20 on 2024-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0050_alter_venda_status_expedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status_expedicao',
            field=models.CharField(blank=True, default='Fazer Cotação', max_length=60, null=True),
        ),
    ]
