# Generated by Django 3.2.20 on 2024-03-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportadora', '0009_transportadora_atuacao'),
        ('venda', '0051_alter_venda_status_expedicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
                ('cotacao', models.CharField(max_length=30)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportadora.transportadora', verbose_name='TRANSPORTADORA')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda', verbose_name='Venda')),
            ],
        ),
    ]
