# Generated by Django 3.2 on 2024-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0052_vendacotacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="data_impressao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
