# Generated by Django 3.2 on 2024-04-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0053_auto_20240428_2041"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="venda",
        #     name="data_impresssao",
        # ),
        migrations.AlterField(
            model_name="venda",
            name="prazo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_pedido",
            field=models.DateTimeField(default="28/04/2024"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="dias_outras_par",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="venda",
            name="dias_prim_par",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="venda",
            name="parcelas",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendaproduto",
            name="quantidade",
            field=models.IntegerField(default=0.0),
        ),
    ]
