# Generated by Django 3.2 on 2024-04-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0054_auto_20240428_2045"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="venda",
        #     name="data_impresssao",
        # ),
        # migrations.AddField(
        #     model_name="venda",
        #     name="prazo",
        #     field=models.CharField(blank=True, max_length=30, null=True),
        # ),
        migrations.CreateModel(
            name="ArquivosVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="venda/"),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos",
                        to="venda.venda",
                    ),
                ),
            ],
        ),
    ]
