# Generated by Django 3.2.20 on 2024-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0055_auto_20240428_2119"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='venda',
        #     name='data_impresssao',
        # ),
        # migrations.AddField(
        #     model_name='venda',
        #     name='prazo',
        #     field=models.CharField(blank=True, max_length=30, null=True),
        # ),
        migrations.AlterField(
            model_name="arquivosvenda",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="arquivos/venda/"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_pedido",
            field=models.DateTimeField(default="29/04/2024"),
        ),
    ]
