# Generated by Django 3.2.20 on 2024-05-14 23:10

from django.db import migrations, models
import django.db.models.deletion
import venda.models


class Migration(migrations.Migration):

    dependencies = [
        ("transportadora", "0009_transportadora_atuacao"),
        ("venda", "0056_auto_20240429_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="redesp_cotacao_transportadora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="REDESPACHO",
                to="transportadora.transportadora",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="redesp_prazo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="redesp_valor_frete",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name="arquivosvenda",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to=venda.models.arquivo_venda_path
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_pedido",
            field=models.DateTimeField(default="14/05/2024"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="transportadora",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TRANSPORTADORA",
                to="transportadora.transportadora",
            ),
        ),
    ]
