# Generated by Django 3.2.20 on 2024-05-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0057_auto_20240514_2010"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='venda',
        #     name='data_impresssao',
        # ),
        # migrations.AlterField(
        #     model_name='venda',
        #     name='data_pedido',
        #     field=models.DateTimeField(default='30/05/2024'),
        # ),
    ]
