# Generated by Django 4.1.7 on 2023-05-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                ("criadoem", models.DateTimeField(auto_now_add=True)),
                ("atualizadoem", models.DateTimeField(auto_now=True)),
                ("num_parcelas", models.IntegerField(default=0)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="receita.categoria",
                    ),
                ),
                (
                    "categoria2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="categoria2",
                        to="receita.categoria",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fornecedor.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "RECEITA",
                "verbose_name_plural": "RECEITAS",
            },
        ),
    ]
