# Generated by Django 3.2.20 on 2023-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
