# Generated by Django 3.2.20 on 2023-08-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_alter_receita_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
