# Generated by Django 3.2.20 on 2023-12-16 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venda', '0042_alter_venda_status_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Status TimeLine',
                'verbose_name_plural': 'Status TimeLines',
            },
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Aberto', 'aberto'), ('Concluído', 'concluido')], max_length=30)),
                ('statusAtual', models.CharField(max_length=30)),
                ('responsavelAtual', models.CharField(max_length=30)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('logado', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suporte.status')),
                ('suporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suporte.suporte')),
            ],
        ),
    ]
