# Generated by Django 3.2.20 on 2023-12-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suporte", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suporte",
            name="responsavel",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.RESTRICT, to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
