# Generated by Django 3.2.20 on 2023-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0002_suporte_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'TimeLine', 'verbose_name_plural': 'TimeLines'},
        ),
        migrations.AlterField(
            model_name='suporte',
            name='status',
            field=models.CharField(choices=[('Aberto', 'aberto'), ('Concluído', 'concluido')], default='Aberto', max_length=30),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='statusAtual',
            field=models.CharField(default='Aberto', max_length=30),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
