# Generated by Django 3.2.20 on 2023-12-22 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0003_auto_20231219_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-suporte'], 'verbose_name': 'TimeLine', 'verbose_name_plural': 'TimeLines'},
        ),
        migrations.AlterField(
            model_name='suporte',
            name='statusAtual',
            field=models.CharField(default='Iniciado', max_length=30),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
