# Generated by Django 3.2.20 on 2024-01-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0004_auto_20231222_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tempo', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Fluxo de trabalho',
                'verbose_name_plural': 'Fluxos de trabalho',
            },
        ),
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tempo', models.IntegerField(default=4)),
                ('ordem', models.IntegerField(default=10)),
                ('proximaacao', models.CharField(max_length=30)),
                ('permite_finalizar', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suporte.workflow')),
            ],
            options={
                'verbose_name': 'Fluxo de trabalho',
                'verbose_name_plural': 'Fluxos de trabalho',
            },
        ),
    ]
