# Generated by Django 3.2.20 on 2024-01-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0005_acoes_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
    ]
