# Generated by Django 3.2.20 on 2024-03-18 19:03

import datetime
from django.db import migrations, models

# from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("suporte", "0006_alter_acoes_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acoes",
            name="permite_finalizar",
        ),
        migrations.AddField(
            model_name="acoes",
            name="instrucoes",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
