# Generated by Django 3.2.20 on 2024-03-19 12:20

import datetime
from django.db import migrations, models

# from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("suporte", "0008_auto_20240319_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="desc_fluxo",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
