# Generated by Django 3.2.20 on 2024-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0009_timeline_desc_fluxo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='status',
            field=models.CharField(choices=[('Aberto', 'aberto'), ('Concluído', 'concluido')], default='Aberto', max_length=30),
        ),
    ]
