# Generated by Django 3.2.20 on 2024-03-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0010_alter_timeline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='status',
        ),
    ]
