# Generated by Django 3.2.20 on 2024-03-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0013_auto_20240326_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subproblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suporte.problema')),
            ],
        ),
    ]
