# Generated by Django 3.2.20 on 2024-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0014_problema_subproblema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
