# Generated by Django 3.2.20 on 2024-03-27 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion

# from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("suporte", "0015_auto_20240326_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="problema",
            name="suporte",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="suporte.suporte",
            ),
            preserve_default=False,
        ),
    ]
