# Generated by Django 3.2.20 on 2024-03-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0016_problema_suporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='suporte',
        ),
        migrations.CreateModel(
            name='ProblemaSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodescricao', models.TextField(max_length=255)),
                ('subprodescricao', models.TextField(max_length=255)),
                ('Subproblema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suporte.subproblema')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suporte.problema')),
                ('suporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suporte.suporte')),
            ],
        ),
    ]
