# Generated by Django 3.2.20 on 2024-03-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0017_auto_20240327_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemasuporte',
            old_name='Subproblema',
            new_name='subproblema',
        ),
    ]
