# Generated by Django 3.2 on 2024-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0018_rename_subproblema_problemasuporte_subproblema'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='concluir',
            field=models.BooleanField(default=False),
        ),
    ]
