# Generated by Django 3.2 on 2024-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0019_suporte_concluir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='concluir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
