# Generated by Django 3.2 on 2024-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0020_alter_suporte_concluir'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='cor',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
