# Generated by Django 3.2 on 2024-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0021_acoes_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproblema',
            name='descricao',
        ),
        migrations.AddField(
            model_name='suporte',
            name='coordenador',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suporte',
            name='dataalerta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
