# Generated by Django 3.2 on 2024-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0024_auto_20240412_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemasuporte',
            name='subprodescricao',
        ),
    ]
