# Generated by Django 3.2 on 2024-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0025_remove_problemasuporte_subprodescricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='proximaacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
