# Generated by Django 3.2 on 2024-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0026_alter_acoes_proximaacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='responsavelAtual',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='status',
            field=models.CharField(choices=[('Aberto', 'aberto'), ('Concluído', 'concluido')], default='Aberto', max_length=100),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='statusAtual',
            field=models.CharField(default='Iniciado', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
