# Generated by Django 3.2 on 2024-04-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0027_auto_20240416_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='fluxo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='suporte.workflow'),
        ),
    ]
