# Generated by Django 3.2 on 2024-04-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0028_alter_timeline_fluxo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='responsavelAtual',
        ),
    ]
