# Generated by Django 3.2 on 2024-04-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0029_remove_suporte_responsavelatual'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='vizualizacao',
            field=models.BooleanField(default=True),
        ),
    ]
