# Generated by Django 3.2 on 2024-04-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0030_timeline_vizualizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='vizualizacao',
            new_name='visualizacao',
        ),
    ]
