# Generated by Django 3.2 on 2024-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0031_rename_vizualizacao_timeline_visualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='cliente_final',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suporte',
            name='tel_cliente_final',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
