# Generated by Django 3.2 on 2024-04-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0032_auto_20240427_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='suporte/')),
                ('suporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='suporte.suporte')),
            ],
        ),
    ]
