# Generated by Django 3.2.20 on 2024-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0033_arquivossuporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivossuporte',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/suporte/'),
        ),
    ]
