# Generated by Django 3.2 on 2024-05-07 18:52

from django.db import migrations, models
import django.db.models.deletion
import suporte.models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0034_alter_arquivossuporte_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivossuporte',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=suporte.models.arquivo_suporte_path),
        ),
        migrations.AlterField(
            model_name='arquivossuporte',
            name='suporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suporte.suporte'),
        ),
    ]
