# Generated by Django 4.1.7 on 2023-05-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_alter_contapagar_formapgto_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormaPagamento",
        ),
    ]
