# Generated by Django 4.1.7 on 2023-05-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0004_alter_venda_formapgto"),
        ("financeiro", "0004_alter_contapagar_formapgto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="formapgto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="venda.formapagamento"
            ),
        ),
    ]
