# Generated by Django 4.1.7 on 2023-05-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_alter_contareceber_formapgto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="parcela",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
