# Generated by Django 4.1.7 on 2023-05-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_alter_contareceber_parcela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="parcela",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
