# Generated by Django 4.1.7 on 2023-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_comissao_delete_comissão"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comissao",
            name="pgto",
        ),
        migrations.AlterField(
            model_name="comissao",
            name="data_comissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="datapagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
