# Generated by Django 4.1.7 on 2023-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("despesa", "0002_saldo"),
        ("compra", "0004_alter_compra_status_compra"),
        (
            "financeiro",
            "0010_remove_comissao_pgto_alter_comissao_data_comissao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contapagar",
            name="compra",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compra.compra",
            ),
        ),
        migrations.AlterField(
            model_name="contapagar",
            name="despesa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="despesa.despesa",
            ),
        ),
    ]
