# Generated by Django 3.2.20 on 2023-08-09 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_alter_contapagar_compra_alter_contapagar_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='financeiro/imagens/<django.db.models.fields.related.ForeignKey>'),
            preserve_default=False,
        ),
    ]
