# Generated by Django 3.2.20 on 2023-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_contareceber_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='financeiro/imagens/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
