# Generated by Django 3.2.20 on 2023-08-10 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_alter_contareceber_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='imagem'),
            preserve_default=False,
        ),
    ]
