# Generated by Django 3.2.20 on 2023-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_alter_contareceber_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/imagens/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
