# Generated by Django 3.2.20 on 2023-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_alter_contareceber_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contareceber',
            options={'verbose_name': 'Contas a receber', 'verbose_name_plural': 'Contas a receber'},
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='financeiro/'),
        ),
    ]
