# Generated by Django 3.2.20 on 2023-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_auto_20230810_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='financeiro'),
        ),
    ]
