# Generated by Django 3.2.20 on 2023-08-11 22:13

from django.db import migrations, models
import financeiro.models


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0018_auto_20230811_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=financeiro.models.path_and_receita_boleto,
            ),
        ),
    ]
