# Generated by Django 3.2.20 on 2023-08-22 10:41

from django.db import migrations, models
import financeiro.models


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0019_alter_contareceber_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=financeiro.models.path_and_despesa_boleto,
            ),
        ),
    ]
