# Generated by Django 3.2.20 on 2023-08-23 00:56

from django.db import migrations, models
import financeiro.models


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0020_contapagar_imagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contapagar",
            old_name="imagem",
            new_name="boleto",
        ),
        migrations.RenameField(
            model_name="contareceber",
            old_name="imagem",
            new_name="boleto",
        ),
        migrations.AddField(
            model_name="contapagar",
            name="comprovante",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=financeiro.models.path_and_despesa_comprovante,
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="comprovante",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=financeiro.models.path_and_receita_comprovante,
            ),
        ),
    ]
