# Generated by Django 3.2.20 on 2023-08-24 17:07

from django.db import migrations, models
import financeiro.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20230822_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to=financeiro.models.path_and_despesa_boleto),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=financeiro.models.path_and_despesa_comprovante),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to=financeiro.models.path_and_receita_boleto),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=financeiro.models.path_and_receita_comprovante),
        ),
    ]
