# Generated by Django 3.2.20 on 2023-09-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_compra_status_compra'),
        ('receita', '0004_receita_usuario'),
        ('despesa', '0005_alter_despesa_options'),
        ('venda', '0017_venda_atualizadopor'),
        ('financeiro', '0022_auto_20230824_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['-datadocumento']},
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='despesa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.despesa'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receita.receita'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.venda'),
        ),
    ]
