# Generated by Django 3.2.20 on 2023-09-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_auto_20230906_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={},
        ),
    ]
