# Generated by Django 3.2.20 on 2023-09-30 22:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0024_alter_contapagar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='dados_boleto',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
