# Generated by Django 3.2.20 on 2023-10-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_alter_contareceber_dados_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
