# Generated by Django 3.2.20 on 2023-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_alter_contareceber_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
