# Generated by Django 3.2.20 on 2023-10-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_alter_contareceber_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
