# Generated by Django 3.2.20 on 2024-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0029_alter_contareceber_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
