# Generated by Django 3.2.20 on 2024-03-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0031_contapagar_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
