# Generated by Django 3.2 on 2024-05-03 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0011_empresa_webmania_classedeimposto'),
        ('financeiro', '0032_alter_contapagar_valor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleExtratosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='extrato/')),
                ('datahora', models.DateTimeField(default=datetime.datetime(2024, 5, 3, 9, 26, 41, 239336))),
                ('conciliado', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.dadosbancarios')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
