# Generated by Django 3.2 on 2024-05-03 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0033_controleextratosbancarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleextratosbancarios',
            name='upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 15, 21, 9, 213491)),
        ),
        migrations.AlterField(
            model_name='controleextratosbancarios',
            name='datahora',
            field=models.DateTimeField(),
        ),
    ]
