# Generated by Django 3.2 on 2024-05-03 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0034_auto_20240503_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleextratosbancarios',
            name='upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 15, 21, 113445)),
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('lancamento', models.CharField(max_length=255)),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('conciliado', models.DateTimeField(blank=True, null=True)),
                ('contaapagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeiro.contapagar')),
                ('contaareceber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeiro.contareceber')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.controleextratosbancarios')),
            ],
        ),
    ]
