# Generated by Django 3.2 on 2024-05-03 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_empresa_webmania_classedeimposto'),
        ('financeiro', '0036_alter_controleextratosbancarios_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleextratosbancarios',
            name='upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 38, 21, 613225)),
        ),
        migrations.AlterUniqueTogether(
            name='controleextratosbancarios',
            unique_together={('datahora', 'conta')},
        ),
        migrations.AlterUniqueTogether(
            name='extratobancario',
            unique_together={('data', 'lancamento', 'origem', 'valor')},
        ),
    ]
