# Generated by Django 3.2 on 2024-05-07 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0037_auto_20240503_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratobancario',
            name='contaapagar',
        ),
        migrations.RemoveField(
            model_name='extratobancario',
            name='contaareceber',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='conciliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeiro.extratobancario'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='conciliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='financeiro.extratobancario'),
        ),
        migrations.AlterField(
            model_name='controleextratosbancarios',
            name='upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 10, 2, 9, 706252)),
        ),
    ]
