# Generated by Django 5.0.6 on 2024-05-18 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0038_auto_20240507_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Contas a pagar', 'verbose_name_plural': 'Contas a pagar'},
        ),
        migrations.AddField(
            model_name='controleextratosbancarios',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='controleextratosbancarios',
            name='upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 21, 32, 1, 660236)),
        ),
    ]
