# Generated by Django 3.2.20 on 2023-10-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasmercadolivre',
            name='expires_in',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Expires IN'),
        ),
        migrations.AlterField(
            model_name='contasmercadolivre',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Ultimo Nome'),
        ),
    ]
