# Generated by Django 3.2.20 on 2023-10-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0002_auto_20231001_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasmercadolivre',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Status'),
        ),
    ]
