# Generated by Django 3.2.20 on 2023-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0003_contasmercadolivre_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasmercadolivre',
            name='expires_now',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
