# Generated by Django 3.2.20 on 2023-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0004_contasmercadolivre_expires_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasmercadolivre',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Refresh Token'),
        ),
    ]
