# Generated by Django 3.2.20 on 2024-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0043_venda_comprovante'),
        ('mercadolivre', '0006_mensagensmercadolivre_packsmercadolivre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnunciosMercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncio', models.CharField(blank=True, max_length=254, null=True, verbose_name='Status')),
                ('adesivado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venda.adesivado')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ContaMercadoLivre', to='mercadolivre.contasmercadolivre')),
                ('torneira', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venda.torneira')),
                ('voltagem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venda.voltagem')),
            ],
        ),
    ]
