# Generated by Django 3.2.20 on 2024-01-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0044_merge_0042_auto_20231218_1812_0043_venda_comprovante'),
        ('mercadolivre', '0008_alter_anunciosmercadolivre_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciosmercadolivre',
            name='adesivado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='venda.adesivado'),
        ),
        migrations.AlterField(
            model_name='anunciosmercadolivre',
            name='torneira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='venda.torneira'),
        ),
        migrations.AlterField(
            model_name='anunciosmercadolivre',
            name='voltagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='venda.voltagem'),
        ),
    ]
