# Generated by Django 3.2.20 on 2024-01-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0009_auto_20240110_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciosmercadolivre',
            name='titulo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Titulo'),
        ),
    ]
