# Generated by Django 4.1.7 on 2023-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="NOME COMPLETO"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=200, verbose_name="NOME FANTASIA"),
                ),
                (
                    "tel_principal",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TELEFONE PRINCIPAL"
                    ),
                ),
                (
                    "tel_contato",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TELEFONE DE CONTATO"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-MAIL"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "insc_estadual",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="INSCRIÇÃO ESTADUAL"
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LOGRADURO"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=30, verbose_name="NÚMERO"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="COMPLEMENTO"
                    ),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=11, verbose_name="CEP"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("PR", "PR"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("RS", "RS"),
                            ("SC", "SC"),
                            ("SE", "SE"),
                            ("SP", "SP"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="ESTADO",
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="CIDADE"),
                ),
                (
                    "status_cliente",
                    models.BooleanField(default=True, verbose_name="ATIVO"),
                ),
            ],
            options={
                "verbose_name": "CLIENTE",
                "verbose_name_plural": "CLIENTES",
            },
        ),
    ]
