# Generated by Django 4.1.7 on 2023-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, verbose_name="BAIRRO"),
        ),
    ]
