# Generated by Django 3.2.20 on 2023-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=15, verbose_name='TELEFONE DE CONTATO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=15, verbose_name='TELEFONE PRINCIPAL'),
        ),
    ]
