# Generated by Django 3.2.20 on 2023-09-15 12:18

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20230802_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
    ]
