# Generated by Django 3.2.20 on 2023-09-15 12:21

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True),
        ),
    ]
