# Generated by Django 3.2.20 on 2023-09-15 12:22

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
    ]
