# Generated by Django 3.2.20 on 2023-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=255, verbose_name='TELEFONE DE CONTATO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=255, verbose_name='TELEFONE PRINCIPAL'),
        ),
    ]
