# Generated by Django 3.2.20 on 2023-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20230920_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contribuinte_inss',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - excesso de sublimite de receita bruta'), ('3', 'Regime Normal')], default='1', max_length=255, verbose_name='Contribuinte INSS'),
        ),
    ]
