# Generated by Django 3.2.20 on 2023-09-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20230921_0729'),
        ('cliente', '0008_cliente_contribuinte_inss'),
    ]

    operations = [
    ]
