# Generated by Django 3.2.20 on 2023-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_merge_20230921_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=60, verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, verbose_name='CIDADE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, verbose_name='COMPLEMENTO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-MAIL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, verbose_name='LOGRADURO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='NOME COMPLETO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(max_length=100, verbose_name='NOME FANTASIA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=15, verbose_name='TELEFONE DE CONTATO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=15, verbose_name='TELEFONE PRINCIPAL'),
        ),
    ]
