# Generated by Django 3.2.20 on 2023-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_auto_20231015_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mercadolivre_id',
            field=models.CharField(blank=True, max_length=60, verbose_name='MERCADOLIVRE_ID'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='PAIS'),
        ),
    ]
