# Generated by Django 3.2.20 on 2023-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_auto_20231029_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
