# Generated by Django 3.2.20 on 2023-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20231127_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='COMPLEMENTO'),
        ),
    ]
