# Generated by Django 3.2.20 on 2024-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_cliente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='CIDADE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contribuinte_inss',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - excesso de sublimite de receita bruta'), ('3', 'Regime Normal')], default='1', max_length=255, null=True, verbose_name='Contribuinte INSS'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='ESTADO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='insc_estadual',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='INSCRIÇÃO ESTADUAL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LOGRADURO'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mercadolivre_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='MERCADOLIVRE_ID'),
        ),
    ]
