# Generated by Django 3.2 on 2024-04-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0017_auto_20240427_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor Padrão',
                'verbose_name_plural': 'Vendedor Padrão',
            },
        ),
    ]
