# Generated by Django 4.1.7 on 2023-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adesivado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "ADESIVADO",
                "verbose_name_plural": "ADESIVADOS",
            },
        ),
        migrations.CreateModel(
            name="Torneira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "TORNEIRA",
                "verbose_name_plural": "TORNEIRAS",
            },
        ),
        migrations.CreateModel(
            name="Voltagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "VOLTAGEM",
                "verbose_name_plural": "VOLTAGENS",
            },
        ),
    ]
