# Generated by Django 4.1.7 on 2023-06-02 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_adesivado_torneira_voltagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="adesivado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="produto.adesivado",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="torneira",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="produto.torneira",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="voltagem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="produto.voltagem",
            ),
            preserve_default=False,
        ),
    ]
