# Generated by Django 3.2.20 on 2023-07-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_adesivado_produto_torneira_produto_voltagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='adesivado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='torneira',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='voltagem',
        ),
        migrations.DeleteModel(
            name='Adesivado',
        ),
        migrations.DeleteModel(
            name='Torneira',
        ),
        migrations.DeleteModel(
            name='Voltagem',
        ),
    ]
