# Generated by Django 3.2.20 on 2023-07-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20230712_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprimaproduto',
            old_name='qtde_mat_prima',
            new_name='quant',
        ),
        migrations.RenameField(
            model_name='materiaprimaproduto',
            old_name='valor_custo',
            new_name='valor',
        ),
    ]
