# Generated by Django 3.2.20 on 2023-07-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20230718_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprimaproduto',
            name='quant',
        ),
        migrations.AddField(
            model_name='produtosmatpri',
            name='quant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='QUANTIDADE'),
        ),
    ]
