# Generated by Django 3.2.20 on 2023-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20230926_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='unidade',
            field=models.CharField(max_length=10, verbose_name='UNIDADE'),
        ),
    ]
