# Generated by Django 3.2.20 on 2023-10-06 10:11

from django.db import migrations, models
import django.db.models.deletion
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_unidademedida_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='xped',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigoproduto',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[produto.models.validate_campos]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unimed',
            field=models.ForeignKey(blank=True, max_length=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.unidademedida', verbose_name='UNIDADE'),
        ),
    ]
