# Generated by Django 3.2.20 on 2023-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
        ('produto', '0012_auto_20231018_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosmatpri',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiaprima.materiaprima'),
        ),
        migrations.DeleteModel(
            name='MateriaPrimaProduto',
        ),
    ]
