# Generated by Django 3.2.20 on 2023-10-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
        ('produto', '0013_auto_20231018_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrimaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='VALOR CUSTO')),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('materiaprima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiaprima.materiaprima', verbose_name='MATERIA PRIMA')),
                ('produto', models.ManyToManyField(blank=True, through='produto.ProdutosMatPri', to='produto.Produto')),
            ],
            options={
                'verbose_name': 'PRODUTO POR MATÉRIA PRIMA',
                'verbose_name_plural': 'PRODUTOS POR MATÉRIAS PRIMAS',
            },
        ),
        migrations.AlterField(
            model_name='produtosmatpri',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.materiaprimaproduto'),
        ),
    ]
