# Generated by Django 3.2.20 on 2023-10-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
        ('produto', '0015_auto_20231020_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMatPri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quantidade')),
                ('materiaprima', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='materiaprima.materiaprima')),
            ],
            options={
                'verbose_name': 'QUANTIDADE DE MATÉRIAS PRIMAS POR PRODUTO',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='unimed',
            field=models.ForeignKey(blank=True, max_length=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.unidademedida'),
        ),
        migrations.DeleteModel(
            name='ProdutosMatPri',
        ),
        migrations.AddField(
            model_name='produtomatpri',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='produtomatpri',
            unique_together={('materiaprima', 'produto')},
        ),
    ]
