# Generated by Django 3.2.20 on 2023-10-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_auto_20231022_0759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produtomatpri',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoproduto', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=120)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('estoque_ini', models.FloatField(blank=True, default=0, null=True)),
                ('status_produto', models.BooleanField(default=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('unimed', models.ForeignKey(blank=True, max_length=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.unidademedida', verbose_name='UNIDADE')),
            ],
            options={
                'verbose_name': 'PRODUTO POR MATÉRIA PRIMA',
                'verbose_name_plural': 'PRODUTOS POR MATÉRIAS PRIMAS',
            },
        ),
        migrations.AddField(
            model_name='produtomatpri',
            name='peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.peca'),
        ),
    ]
