# Generated by Django 3.2.20 on 2023-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_auto_20231025_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
