# Generated by Django 3.2.20 on 2023-10-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_alter_peca_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomatpri',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.peca'),
        ),
        migrations.AlterField(
            model_name='produtomatpri',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.produto', verbose_name='Produto'),
        ),
    ]
