# Generated by Django 3.2.20 on 2023-10-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0003_alter_materiaprima_options'),
        ('produto', '0019_auto_20231026_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'PEÇA', 'verbose_name_plural': 'PECAS'},
        ),
        migrations.AddField(
            model_name='peca',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='produtomatpri',
            unique_together={('materiaprima', 'peca'), ('materiaprima', 'produto')},
        ),
    ]
