# Generated by Django 3.2.20 on 2023-10-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0021_auto_20231026_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='unimed',
            field=models.ForeignKey(blank=True, max_length=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.unidademedida'),
        ),
        migrations.AlterField(
            model_name='produtomatpri',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
