# Generated by Django 3.2.20 on 2023-11-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_merge_0006_auto_20231008_1743_0006_auto_20231012_0838'),
        ('produto', '0022_auto_20231031_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
