# Generated by Django 3.2.20 on 2023-11-22 21:51

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0023_produto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[produto.models.validate_campos]),
        ),
    ]
