# Generated by Django 3.2.20 on 2024-02-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0025_alter_peca_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque_ini',
            new_name='estoque_127',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_220',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
