# Generated by Django 3.2.20 on 2024-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0026_auto_20240220_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="altura",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="comprimento",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="largura",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
