# Generated by Django 4.1.7 on 2023-07-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("despesa", "0002_saldo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterField(
            model_name="despesa",
            name="categoria2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="categoria2",
                to="despesa.categoria2",
            ),
        ),
    ]
