# Generated by Django 4.1.7 on 2023-07-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("despesa", "0003_categoria2_alter_despesa_categoria2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria2",
            options={
                "verbose_name": "Categoria 2",
                "verbose_name_plural": "Categorias 2",
            },
        ),
        migrations.RemoveField(
            model_name="despesa",
            name="categoria2",
        ),
        migrations.AddField(
            model_name="categoria",
            name="categoria2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="categoria2",
                to="despesa.categoria2",
            ),
            preserve_default=False,
        ),
    ]
