# Generated by Django 3.2.20 on 2023-09-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_alter_categoria2_options_remove_despesa_categoria2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['criadoem'], 'verbose_name': 'DESPESA', 'verbose_name_plural': 'DESPESAS'},
        ),
    ]
