# Generated by Django 4.1.7 on 2023-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportadora", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportadora",
            name="cep",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="complemento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("PR", "PR"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("RS", "RS"),
                    ("SC", "SC"),
                    ("SE", "SE"),
                    ("SP", "SP"),
                    ("TO", "TO"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="insc_estadual",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="logradouro",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="mei",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="numero",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="telefone1",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="telefone2",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
