# Generated by Django 4.1.7 on 2023-05-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transportadora", "0002_transportadora_cep_transportadora_cidade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transportadora",
            old_name="telefone1",
            new_name="tel_contato",
        ),
        migrations.RenameField(
            model_name="transportadora",
            old_name="telefone2",
            new_name="tel_principal",
        ),
        migrations.AddField(
            model_name="transportadora",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transportadora",
            name="nome_fantasia",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportadora",
            name="status_transportadora",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transportadora",
            name="nome",
            field=models.CharField(max_length=200),
        ),
    ]
