# Generated by Django 3.2.20 on 2024-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportadora', '0007_rotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotas',
            name='cidade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
