# Generated by Django 3.2.20 on 2024-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportadora', '0008_alter_rotas_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='atuacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
