# Generated by Django 4.1.7 on 2023-05-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funcionario", "0001_initial"),
        ("produto", "0001_initial"),
        ("materiaprima", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtde_producao_diaria", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PrevisaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producao", models.IntegerField()),
                ("inicio", models.DateField(unique=True)),
                ("fim", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoAcabado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroserie", models.CharField(max_length=200)),
                ("valor_venda", models.FloatField()),
                ("valor_custototal", models.FloatField()),
                ("valor_custo_material", models.FloatField()),
                ("valor_custo_imposto", models.FloatField()),
                ("valor_custo_producao", models.FloatField()),
                ("valor_custo_administracao", models.FloatField()),
                ("valor_custo_venda", models.FloatField()),
                ("data_producao", models.DateTimeField()),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "PRODUTO ACABADO",
                "verbose_name_plural": "PRODUTOS ACABADOS",
            },
        ),
        migrations.CreateModel(
            name="Montadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="funcionario.funcionario",
                    ),
                ),
                (
                    "setor_montagem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="producao.setor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MateriaPrimaProdutoAcabado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        null=True,
                        verbose_name="VALOR CUSTO",
                    ),
                ),
                (
                    "materiaprimausada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="materiaprima.materiaprima",
                        verbose_name="MATERIA PRIMA",
                    ),
                ),
                (
                    "produtoacabado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="producao.produtoacabado",
                        verbose_name="PRODUTO",
                    ),
                ),
            ],
            options={
                "verbose_name": "MATÉRIA PRIMA PRODUTO ACABADO",
                "verbose_name_plural": "MATÉRIA PRIMA PRODUTOS ACABADOS",
            },
        ),
        migrations.CreateModel(
            name="MateriaPrimaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quant", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=9, null=True
                    ),
                ),
                (
                    "materiaprimausada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="mpusado",
                        to="materiaprima.materiaprima",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="mpproduto",
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria prima Produto",
                "verbose_name_plural": "Matéria prima Produtos",
            },
        ),
    ]
