# Generated by Django 4.1.7 on 2023-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LimiteProducaoDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtde", models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Config",
        ),
    ]
