# Generated by Django 4.1.7 on 2023-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0002_limiteproducaodiaria_delete_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previsaoestoque",
            name="fim",
        ),
        migrations.RemoveField(
            model_name="previsaoestoque",
            name="inicio",
        ),
    ]
