# Generated by Django 4.1.7 on 2023-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0003_remove_previsaoestoque_fim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtoacabado",
            name="hora",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produtoacabado",
            name="status",
            field=models.CharField(
                choices=[
                    ("faltandomateriaprima", "Faltando Materia Prima"),
                    ("montagem", "Montagem"),
                    ("eletrica", "Elétrica"),
                    ("refrigeracao", "Refrigeração"),
                    ("acabamento", "Acabamento"),
                    ("estoque", "Estoque"),
                ],
                default="montagem",
                max_length=255,
            ),
        ),
    ]
