# Generated by Django 4.1.7 on 2023-06-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_produto_adesivado_produto_torneira_produto_voltagem"),
        ("producao", "0005_historicomontagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoacabado",
            name="data_producao",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="numeroserie",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="produto.produto",
            ),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_administracao",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_imposto",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_material",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_producao",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_venda",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custototal",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_venda",
            field=models.FloatField(blank=True),
        ),
    ]
