# Generated by Django 4.1.7 on 2023-06-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0006_alter_produtoacabado_data_producao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_venda",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
