# Generated by Django 4.1.7 on 2023-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0007_alter_produtoacabado_valor_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoacabado",
            name="data_producao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_administracao",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_imposto",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_material",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_producao",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custo_venda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="valor_custototal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
