# Generated by Django 4.1.7 on 2023-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0008_alter_produtoacabado_data_producao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtoacabado",
            old_name="hora",
            new_name="hora_inicio",
        ),
        migrations.AddField(
            model_name="produtoacabado",
            name="hora_momento",
            field=models.DateField(auto_now=True),
        ),
    ]
