# Generated by Django 4.1.7 on 2023-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0009_rename_hora_produtoacabado_hora_inicio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicomontagem",
            old_name="tempo_gasto_minutos",
            new_name="duracao",
        ),
        migrations.AddField(
            model_name="produtoacabado",
            name="duracao",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="hora_inicio",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="hora_momento",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
