# Generated by Django 4.1.7 on 2023-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "producao",
            "0010_rename_tempo_gasto_minutos_historicomontagem_duracao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TempoDesejadoProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("faltandomateriaprima", "Faltando Materia Prima"),
                            ("montagem", "Montagem"),
                            ("eletrica", "Elétrica"),
                            ("refrigeracao", "Refrigeração"),
                            ("acabamento", "Acabamento"),
                            ("estoque", "Estoque"),
                        ],
                        default="montagem",
                        max_length=255,
                    ),
                ),
                ("tempo_verde", models.FloatField(default=0)),
                ("tempo_amarelo", models.FloatField(default=0)),
            ],
        ),
    ]
