# Generated by Django 4.1.7 on 2023-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0011_tempodesejadoproducao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtoacabado",
            name="hora_fim",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicomontagem",
            name="status",
            field=models.CharField(
                choices=[
                    ("faltandomateriaprima", "Faltando Materia Prima"),
                    ("montagem", "Montagem"),
                    ("eletrica", "Elétrica"),
                    ("refrigeracao", "Refrigeração"),
                    ("acabamento", "Acabamento"),
                    ("embalagem", "Embalagem"),
                    ("estoque", "Estoque"),
                ],
                default="montagem",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="produtoacabado",
            name="status",
            field=models.CharField(
                choices=[
                    ("faltandomateriaprima", "Faltando Materia Prima"),
                    ("montagem", "Montagem"),
                    ("eletrica", "Elétrica"),
                    ("refrigeracao", "Refrigeração"),
                    ("acabamento", "Acabamento"),
                    ("embalagem", "Embalagem"),
                    ("estoque", "Estoque"),
                ],
                default="montagem",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tempodesejadoproducao",
            name="status",
            field=models.CharField(
                choices=[
                    ("faltandomateriaprima", "Faltando Materia Prima"),
                    ("montagem", "Montagem"),
                    ("eletrica", "Elétrica"),
                    ("refrigeracao", "Refrigeração"),
                    ("acabamento", "Acabamento"),
                    ("embalagem", "Embalagem"),
                    ("estoque", "Estoque"),
                ],
                default="montagem",
                max_length=255,
            ),
        ),
    ]
