# Generated by Django 4.1.7 on 2023-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0012_produtoacabado_hora_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicomontagem",
            name="hora",
        ),
        migrations.AddField(
            model_name="historicomontagem",
            name="hora_fim",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="historicomontagem",
            name="hora_inicio",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
