# Generated by Django 4.1.7 on 2023-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0013_remove_historicomontagem_hora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoacabado",
            name="hora_inicio",
            field=models.DateTimeField(),
        ),
    ]
