# Generated by Django 4.1.7 on 2023-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0014_alter_produtoacabado_hora_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicomontagem",
            name="produtoacabado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="producao.produtoacabado",
                verbose_name="PRODUTOACABADO",
            ),
        ),
    ]
