# Generated by Django 3.2.20 on 2023-07-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_alter_historicomontagem_produtoacabado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MateriaPrimaProduto',
        ),
    ]
