# Generated by Django 3.2.20 on 2023-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_delete_materiaprimaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteproducaodiaria',
            name='qtde',
            field=models.IntegerField(default=5),
        ),
    ]
