# Generated by Django 3.2.20 on 2023-08-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0007_auto_20230718_1747"),
        ("producao", "0017_alter_limiteproducaodiaria_qtde"),
    ]

    operations = [
        migrations.RenameField(
            model_name="limiteproducaodiaria",
            old_name="qtde",
            new_name="quantidade",
        ),
        migrations.AddField(
            model_name="limiteproducaodiaria",
            name="produto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="produto.produto",
            ),
            preserve_default=False,
        ),
    ]
