# Generated by Django 3.2.20 on 2023-08-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0018_auto_20230812_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteproducaodiaria',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
