# Generated by Django 3.2.20 on 2023-10-25 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0017_auto_20231025_1415'),
        ('producao', '0019_alter_limiteproducaodiaria_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaAcabada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dataproducao', models.DateField()),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('peca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='produto.peca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PEÇA',
                'verbose_name_plural': 'PEÇAS',
            },
        ),
    ]
