# Generated by Django 3.2.20 on 2023-10-31 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_auto_20231031_0845'),
        ('producao', '0020_pecaacabada'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteproducaodiaria',
            name='peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.peca'),
        ),
        migrations.AlterField(
            model_name='limiteproducaodiaria',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
