# Generated by Django 3.2.20 on 2023-10-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_auto_20231031_0845'),
        ('producao', '0021_auto_20231031_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteproducaodiaria',
            name='peca',
        ),
        migrations.AlterField(
            model_name='limiteproducaodiaria',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.CreateModel(
            name='LimiteProducaoDiariaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.peca')),
            ],
        ),
    ]
