# Generated by Django 3.2.20 on 2023-11-23 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0023_produto_empresa"),
        ("producao", "0022_auto_20231031_1621"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="limiteproducaodiaria",
            name="id",
        ),
        migrations.RemoveField(
            model_name="limiteproducaodiariapeca",
            name="id",
        ),
        migrations.AlterField(
            model_name="limiteproducaodiaria",
            name="produto",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="produto.produto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="limiteproducaodiariapeca",
            name="peca",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="produto.peca",
            ),
            preserve_default=False,
        ),
    ]
