# Generated by Django 3.2.20 on 2023-10-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_regimetributario'),
        ('funcionario', '0002_extenduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='city',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
