# Generated by Django 3.2.20 on 2023-10-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20231006_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='r',
            new_name='usuario',
        ),
    ]
