# Generated by Django 3.2.20 on 2023-11-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_rename_r_extenduser_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='mercadolivre_user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
