# Generated by Django 3.2.20 on 2023-11-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_extenduser_mercadolivre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='mercadolivre_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
