# Generated by Django 4.1.7 on 2023-05-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
        ("materiaprima", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("criadoem", models.DateTimeField(auto_now_add=True)),
                ("atualizadoem", models.DateTimeField(auto_now=True)),
                ("num_parcelas", models.IntegerField(default=0)),
                ("previsaoentrega", models.DateField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="fornecedor.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
            },
        ),
        migrations.CreateModel(
            name="CompraMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField(default=1)),
                ("detalhes", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="compra.compra"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="materiaprima.materiaprima",
                    ),
                ),
            ],
        ),
    ]
