# Generated by Django 4.1.7 on 2023-06-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compramateriaprima",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
