# Generated by Django 4.1.7 on 2023-06-23 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0002_alter_compramateriaprima_quantidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="status_compra",
            field=models.CharField(
                choices=[("orcamento", "Orçamento"), ("autorizado", "Autorizado")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
