# Generated by Django 4.1.7 on 2023-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compra", "0003_compra_status_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="status_compra",
            field=models.CharField(
                choices=[("solicitado", "Solicitado"), ("recebido", "Recebido")],
                max_length=50,
            ),
        ),
    ]
