# Generated by Django 3.2.20 on 2023-10-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_compra_status_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pedido',
            field=models.FileField(blank=True, null=True, upload_to='compra/pedido/'),
        ),
    ]
