# Generated by Django 4.1.7 on 2023-05-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chavedeacesso",
                    models.CharField(max_length=255, verbose_name="Chave de Acesso"),
                ),
                (
                    "naturezadaoperacao",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Natureza da Operação"
                    ),
                ),
                (
                    "numeroserie",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Numero de Serie"
                    ),
                ),
                (
                    "protocoloautorizacaodeuso",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Protocolo de Autorização",
                    ),
                ),
                (
                    "nome_destinatario",
                    models.CharField(max_length=255, null=True, verbose_name="Nome"),
                ),
                (
                    "cnpj_destinatario",
                    models.CharField(max_length=255, verbose_name="Cnpj"),
                ),
                (
                    "bairro_destinatario",
                    models.CharField(max_length=255, null=True, verbose_name="Bairro"),
                ),
                (
                    "cep_destinatario",
                    models.CharField(max_length=255, null=True, verbose_name="Cep"),
                ),
                (
                    "data_emissao",
                    models.DateField(max_length=255, verbose_name="Data Emissão"),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Forma de Pagamento"
                    ),
                ),
                (
                    "base_calculo_icms",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Base Calculo Icms"
                    ),
                ),
                (
                    "valor_icms",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_pis",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_total_produtos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_do_frete",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_do_seguro",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "outras_despesas",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_total_ipi",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_da_cofins",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_total_da_nota",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fornecedorNFCompra",
                        to="fornecedor.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Fiscal Compra",
                "verbose_name_plural": "Notas Fiscais de compra",
            },
        ),
        migrations.CreateModel(
            name="NFItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materiaprima",
                    models.CharField(max_length=255, verbose_name="Produto"),
                ),
                (
                    "codigo_produto",
                    models.CharField(max_length=255, verbose_name="Codigo Produto"),
                ),
                (
                    "descricao",
                    models.TextField(max_length=255, verbose_name="Descrição"),
                ),
                ("ncm_sh", models.CharField(max_length=255, verbose_name="Ncm Sh")),
                ("o_csqn", models.CharField(max_length=255, verbose_name="O Csqn")),
                ("cfop", models.CharField(max_length=255, verbose_name="Cfop")),
                ("un", models.CharField(max_length=255, verbose_name="Unidade")),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "b_calc_imcs",
                    models.CharField(max_length=255, verbose_name="Base Calculo Icms"),
                ),
                (
                    "valor_icms",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "valor_ipi",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "aliq_icms",
                    models.CharField(max_length=255, verbose_name="Aliq Icms"),
                ),
                ("aliq_ipi", models.CharField(max_length=255, verbose_name="Aliq Ipi")),
                (
                    "notafiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notafiscal.nfcompra",
                    ),
                ),
            ],
        ),
    ]
