# Generated by Django 3.2.20 on 2023-12-01 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venda', '0039_auto_20231129_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 11, 15, 13, 567710))),
                ('status', models.CharField(max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.vendaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTimeLineGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status TimeLine',
                'verbose_name_plural': 'Status TimeLines',
            },
        ),
        migrations.CreateModel(
            name='GarantiaTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 12, 1, 11, 15, 13, 568710))),
                ('atualizadopor', models.CharField(max_length=255)),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantia.garantia')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantia.statustimelinegarantia')),
            ],
            options={
                'verbose_name': 'TimeLine',
                'verbose_name_plural': 'TimeLines',
                'ordering': ['-garantia'],
            },
        ),
    ]
