# Generated by Django 3.2.20 on 2023-12-01 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status Garantia',
                'verbose_name_plural': 'Status Garantias',
            },
        ),
        migrations.AlterField(
            model_name='garantia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 13, 38, 3, 927685)),
        ),
        migrations.AlterField(
            model_name='garantiatimeline',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 13, 38, 3, 928723)),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantia.statusgarantia'),
        ),
    ]
