# Generated by Django 3.2.20 on 2023-12-02 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0002_auto_20231201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 20, 43, 843749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='status',
            field=models.ForeignKey(default='aberto', on_delete=django.db.models.deletion.CASCADE, to='garantia.statusgarantia'),
        ),
        migrations.AlterField(
            model_name='garantiatimeline',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 20, 43, 843749, tzinfo=utc)),
        ),
    ]
