# Generated by Django 3.2.20 on 2023-12-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garantia', '0004_auto_20231202_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garantia.statusgarantia'),
        ),
    ]
