# Generated by Django 3.2.20 on 2023-10-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'verbose_name': 'Materia Prima', 'verbose_name_plural': 'Materias Primas'},
        ),
    ]
