# Generated by Django 3.2.20 on 2023-10-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_alter_materiaprima_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'ordering': ['nome'], 'verbose_name': 'Materia Prima', 'verbose_name_plural': 'Materias Primas'},
        ),
    ]
