# Generated by Django 3.2.20 on 2023-09-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
    ]
