# Generated by Django 3.2.20 on 2023-09-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=200)),
                ('num_banco', models.IntegerField()),
                ('agencia', models.CharField(max_length=200)),
                ('conta', models.CharField(max_length=200)),
                ('dac', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
    ]
