# Generated by Django 3.2.20 on 2023-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20230915_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='num_banco',
            field=models.CharField(max_length=200),
        ),
    ]
