# Generated by Django 3.2.20 on 2023-09-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_dadosbancarios_num_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regimetributario',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - excesso de sublimite de receita bruta'), ('3', 'Regime Normal')], max_length=100, null=True),
        ),
    ]
