# Generated by Django 3.2.20 on 2023-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_regimetributario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modalidade_frete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='presenca',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
