# Generated by Django 3.2.20 on 2023-10-12 11:38

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_regimetributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True),
        ),
    ]
