# Generated by Django 3.2.20 on 2023-10-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20231008_1743'),
        ('empresa', '0006_auto_20231012_0838'),
    ]

    operations = [
    ]
