# Generated by Django 3.2.20 on 2023-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_empresa_natureza_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='webmania_accesstoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='webmania_accesstokensecret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='webmania_consumerkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='webmania_consumersecret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
