# Generated by Django 3.2.20 on 2023-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_auto_20231121_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='webmania_bearer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
