# Generated by Django 3.2.20 on 2023-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_empresa_webmania_bearer'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='webmania_classedeimposto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
