# Generated by Django 4.1.7 on 2023-05-09 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materiaprima", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnderecoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoAcabado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueProdutoAcabado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtde", models.FloatField()),
                (
                    "enderecoestoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.enderecoestoque",
                    ),
                ),
                (
                    "produtoacabado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.produtoacabado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtde",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "enderecoestoque",
                    models.ForeignKey(
                        default=6,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.enderecoestoque",
                    ),
                ),
                (
                    "materiaprima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="materiaprima.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Materia Prima",
                "verbose_name_plural": "Estoque de Materias Prima",
                "ordering": ["materiaprima"],
            },
        ),
        migrations.CreateModel(
            name="ConferenciaEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(blank=True, max_length=255, null=True)),
                ("qtde", models.IntegerField()),
                ("data", models.DateField(default=datetime.date.today)),
                ("conferencia", models.IntegerField(default=0)),
                ("relatorio", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="estoque.estoquemateriaprima",
                    ),
                ),
            ],
        ),
    ]
