# Generated by Django 3.2.20 on 2023-07-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquemateriaprima',
            name='enderecoestoque',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='estoque.enderecoestoque'),
        ),
    ]
