# Generated by Django 3.2.20 on 2023-08-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoquemateriaprima_enderecoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquemateriaprima',
            name='enderecoestoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='estoque.enderecoestoque'),
        ),
    ]
