# Generated by Django 3.2.20 on 2023-10-25 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_auto_20231025_1415'),
        ('estoque', '0004_auto_20231018_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoquePecaAcabada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('enderecoestoque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='estoque.enderecoestoque')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.peca')),
            ],
            options={
                'verbose_name': 'Estoque Produtos Manufaturados',
                'verbose_name_plural': 'Estoque Produtos Manufaturados',
                'ordering': ['peca'],
            },
        ),
        migrations.CreateModel(
            name='ConferenciaEstoquePeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('conferencia', models.IntegerField(default=0)),
                ('relatorio', models.CharField(blank=True, max_length=255, null=True)),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.peca')),
            ],
        ),
    ]
