# Generated by Django 3.2.20 on 2023-10-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_conferenciaestoquepeca_estoquepecaacabada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenciaestoquepeca',
            name='atualizadoem',
        ),
        migrations.RemoveField(
            model_name='conferenciaestoquepeca',
            name='criadoem',
        ),
    ]
