# Generated by Django 4.1.7 on 2023-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone1", models.CharField(blank=True, max_length=11, null=True)),
                ("telefone2", models.CharField(blank=True, max_length=11, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("cpf", models.CharField(blank=True, max_length=14, null=True)),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("mei", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "insc_estadual",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("logradouro", models.CharField(blank=True, max_length=200, null=True)),
                ("numero", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cep", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("PR", "PR"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("RS", "RS"),
                            ("SC", "SC"),
                            ("SE", "SE"),
                            ("SP", "SP"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "FORNECEDOR",
                "verbose_name_plural": "FORNECEDORES",
                "ordering": ["nome"],
            },
        ),
    ]
