# Generated by Django 4.1.7 on 2023-06-13 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedor",
            },
        ),
        migrations.RenameField(
            model_name="fornecedor",
            old_name="telefone1",
            new_name="tel_contato",
        ),
        migrations.RenameField(
            model_name="fornecedor",
            old_name="telefone2",
            new_name="tel_principal",
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="nome_fantasia",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="status_transportadora",
            field=models.BooleanField(default=True),
        ),
    ]
