# Generated by Django 4.1.7 on 2023-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedor", "0002_alter_fornecedor_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fornecedor",
            old_name="status_transportadora",
            new_name="status_fornecedor",
        ),
    ]
