# Generated by Django 3.2.20 on 2023-09-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_rename_status_transportadora_fornecedor_status_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
