# Generated by Django 3.2.20 on 2023-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0004_alter_fornecedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
