# Generated by Django 3.2.20 on 2023-10-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_auto_20230920_2257'),
        ('fornecedor', '0005_auto_20230921_0722'),
    ]

    operations = [
    ]
