# Generated by Django 3.2.20 on 2023-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0007_auto_20231012_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UfsCidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=200)),
            ],
        ),
    ]
